create database sq;
use sq;
-- 1. Supplier Table
CREATE TABLE IF NOT EXISTS supplier (
 sup_id TINYINT PRIMARY KEY,
 sup_name VARCHAR(255),
 address TEXT
);
-- 2. Categories Table
CREATE TABLE IF NOT EXISTS categories (
 cat_id TINYINT PRIMARY KEY,
 cat_name VARCHAR(255)
);
-- 3. Employees Table
CREATE TABLE IF NOT EXISTS employees (
 emp_id TINYINT PRIMARY KEY,
 emp_name VARCHAR(255),
 hire_date VARCHAR(255)
);
-- 4. Customers Table
CREATE TABLE IF NOT EXISTS customers (
 cust_id SMALLINT PRIMARY KEY,
 cust_name VARCHAR(255),
 address TEXT
);
-- 5. Products Table
CREATE TABLE IF NOT EXISTS products (
 prod_id TINYINT PRIMARY KEY,
 prod_name VARCHAR(255),
 sup_id TINYINT,
 cat_id TINYINT,
 price DECIMAL(10,2),
 FOREIGN KEY (sup_id) REFERENCES supplier(sup_id)
 ON UPDATE CASCADE ON DELETE CASCADE,
 FOREIGN KEY (cat_id) REFERENCES categories(cat_id)
 ON UPDATE CASCADE ON DELETE CASCADE
);
-- 6. Orders Table
CREATE TABLE IF NOT EXISTS orders (
 ord_id SMALLINT PRIMARY KEY,
 cust_id SMALLINT,
 emp_id TINYINT,
 order_date VARCHAR(255),
 FOREIGN KEY (cust_id) REFERENCES customers(cust_id)
 ON UPDATE CASCADE ON DELETE CASCADE,
 FOREIGN KEY (emp_id) REFERENCES employees(emp_id)
 ON UPDATE CASCADE ON DELETE CASCADE
);
-- 7. Order_Details Table
CREATE TABLE IF NOT EXISTS order_details (
 ord_detID SMALLINT AUTO_INCREMENT PRIMARY KEY,
 ord_id SMALLINT,
 prod_id TINYINT,
 quantity TINYINT,
 each_price DECIMAL(10,2),
 total_price DECIMAL(10,2),
 FOREIGN KEY (ord_id) REFERENCES orders(ord_id)
 ON UPDATE CASCADE ON DELETE CASCADE,
 FOREIGN KEY (prod_id) REFERENCES products(prod_id)
 ON UPDATE CASCADE ON DELETE CASCADE
);
-- Analysis Questions

select * from customers;
select *from orders;
select *from categories;
select *from empinfo;
select *from employees;
select *from order_details;
select *from products;
select *from supplier;


# 1.Customer Insights
# Gain an understanding of customer engagement and purchasing behavior.

-- How many unique customers have placed orders?
select count(distinct cust_id) from Customers;

-- Which customers have placed the highest number of orders?
select c.cust_name,c.cust_id,count(o.cust_id) as freq
      from customers as c
		 join orders as o
         on c.cust_id=o.cust_id
         group by cust_id,c.cust_name
         order by freq desc
         limit 1;

-- What is the total and average purchase value per customer?
select c.cust_id,c.cust_name,sum(od.total_price)as total_purchase_value,
avg(od.total_price) as average_purchase_value
from customers as c
join orders as o on c.cust_id=o.cust_id
join order_details as od on o.ord_id=od.ord_id
group by c.cust_id;

-- Who are the top 5 customers by total purchase amount?
select c.cust_id,c.cust_name,sum(od.total_price)as total_purchase_value
from customers as c
join orders as o on c.cust_id=o.cust_id
join order_details as od on o.ord_id=od.ord_id
group by c.cust_id
order by total_purchase_value desc
limit 5;

-- 2. Product Performance
-- Evaluate how well products are performing in terms of sales and revenue.

-- How many products exist in each category?
select c.cat_id,c.cat_name,count(p.cat_id) as count_of_products
from products as p
join categories as c 
on c.cat_id=p.cat_id
group by p.cat_id;


-- What is the average price of products by category?
select c.cat_id,c.cat_name,avg(p.cat_id) as average_price
from products as p
join categories as c 
on c.cat_id=p.cat_id
group by p.cat_id;


-- Which products have the highest total sales volume (by quantity)?
select p.prod_id,p.prod_name,sum(od.quantity) as volume
from products as p
join order_details as od
on p.prod_id=od.prod_id
group by od.prod_id
order by volume desc 
limit 1;

-- What is the total revenue generated by each product?
select p.prod_id,p.prod_name,sum(od.total_price) as total_revenue
from products as p
join order_details as od
on p.prod_id=od.prod_id
group by od.prod_id;

-- How do product sales vary by category and supplier?
SELECT
    c.Cat_Name,
    s.Sup_Name,
    SUM(od.Total_Price) AS Total_Sales,
    SUM(od.Quantity) AS Total_Quantity_Sold
FROM Order_Details AS od
JOIN Products AS p ON od.Prod_ID = p.Prod_ID
JOIN Categories AS c ON p.Cat_ID = c.Cat_ID
JOIN Supplier AS s ON p.Sup_ID = s.Sup_ID
GROUP BY c.Cat_Name, s.Sup_Name
ORDER BY Total_Sales DESC;

-- 3. Sales and Order Trends
-- Analyze business performance through orders and revenue over time.

-- How many orders have been placed in total?
select count(ord_id) from orders;

-- What is the average value per order?
select sum(total_price) / count(distinct ord_id) as Averageordervalue 
from order_details ;

-- On which dates were the most orders placed?
select o.order_date,sum(od.quantity) as quant
from orders as o
join order_details as od
on o.ord_id=od.ord_id
group by o.order_date
order by quant desc
limit 1;

-- What are the monthly trends in order volume and revenue?
SELECT
    DATE_FORMAT(STR_TO_DATE(o.Order_Date, '%Y-%m-%d'), '%Y-%m') AS OrderMonth,
    COUNT(DISTINCT o.Ord_ID) AS OrderVolume,
    SUM(od.Total_Price) AS TotalRevenue
FROM Orders o
JOIN Order_Details od ON o.Ord_ID = od.Ord_ID
GROUP BY OrderMonth
ORDER BY OrderMonth;

-- How do order patterns vary across weekdays and weekends?
select case when DAYNAME(STR_TO_DATE(Order_date,'%Y-%m-%d')) in ('Saturday','Sunday') then 'Weekend'
else 'Weekday'
End as Daytype,
count(ord_id) as TotalOrders
from Orders
Group By Daytype;


-- 4️. Supplier Contribution
-- Identify the most active and profitable suppliers.

-- How many suppliers are there in the database?
select count(sup_id) from supplier;

-- Which supplier provides the most products?
select s.sup_id,s.sup_name,count(p.sup_id) as most_supplier_products
           from supplier as s
           join products as p
           on s.sup_id=p.sup_id
           group by p.sup_id
           order by most_supplier_products desc
           limit 1;

-- What is the average price of products from each supplier?
select s.sup_id,s.sup_name,avg(od.total_price)
           from supplier as s
           join products as p on s.sup_id=p.sup_id
           join order_details as od on od.prod_id=p.prod_id
           group by p.sup_id;


-- Which suppliers contribute the most to total product sales (by revenue)?
select s.sup_id,s.sup_name,sum(od.total_price) as Total_sale
           from supplier as s
           join products as p on s.sup_id=p.sup_id
           join order_details as od on od.prod_id=p.prod_id
           group by p.sup_id
           order by Total_sale desc
           limit 1;


-- 5️. Employee Performance
-- Assess how employees are handling and influencing sales.

-- How many employees have processed orders?
select count(se.emp_id) as Emp_processed_orders
from employees as se
join orders as o on se.Emp_id=o.ord_id;

-- Which employees have handled the most orders?
select emp_id,count(emp_id) as Count_emp
      from orders
      group by emp_id
      order by Count_emp desc
      limit 1;

-- What is the total sales value processed by each employee?
SELECT 
    se.emp_name AS EmployeeName,
    SUM(od.Total_price) AS TotalSalesValue
FROM employees se
JOIN orders o ON se.emp_id = o.emp_id
JOIN order_details od ON o.ord_id = od.ord_id
GROUP BY se.emp_name
ORDER BY TotalSalesValue DESC;


-- What is the average order value handled per employee?
select e.emp_name as EmployeeName,
sum(od.Total_price) / count(Distinct od.ord_id) as AverageOrderVAlue
from employees e
join orders o ON e.emp_id = o.emp_id
JOIN order_details od ON o.ord_id = od.ord_id
GROUP BY e.emp_name
ORDER BY AverageOrderVAlue DESC;

-- 6️. Order Details Dezep Dive
-- Explore item-level sales patterns and pricing behavior.

-- What is the relationship between quantity ordered and total price?
select Quantity,Each_price,Total_Price from Order_details;

-- What is the average quantity ordered per product?
select p.prod_name as Productname,
avg(od.quantity) as AverageQuantityOrdered
from order_details od
join products p on od.prod_id=p.prod_id
group by p.prod_name
order by AverageQuantityOrdered DESC;

-- How does the unit price vary across products and orders?
SELECT
    p.prod_Name AS ProductName,
    MIN(od.Each_price) AS MinimumPrice,
    MAX(od.Each_price) AS MaximumPrice,
    AVG(od.Each_price) AS AveragePrice,
    stddev(od.Each_price) AS PriceStandardDeviation
FROM Order_Details od
JOIN Products p ON od.Prod_ID = p.Prod_ID
GROUP BY p.prod_Name
ORDER BY Prod_Name;
